create table if not exists stat_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(20) NOT NULL,
    uri VARCHAR(50) NOT NULL,
    ip VARCHAR(39) NOT NULL,
    request_time TIMESTAMP NOT NULL
);
